---
RecipeFormatVersion: "2020-01-25"
ComponentName: com.devopstar.json.gzip
ComponentVersion: NEXT_PATCH
ComponentDescription: This component takes a stream of JSON messages from StreamManager and batches them into a gzip file. It uses a JSON Line (JSONL) format for the messages.
ComponentPublisher: Nathan Glover
ComponentDependencies:
  aws.greengrass.StreamManager:
    VersionRequirement: ^2.0.0
    DependencyType: HARD
ComponentConfiguration:
  DefaultConfiguration:
    Path: "/tmp/greengrass/gzip"
    Interval: "30"
    Processor:
      StreamName: "BatchMessageStream"
      BatchSize: "200"
    Uploader:
      BucketName: "my-bucket"
      Prefix: "sample-devices"
    LogLevel: "INFO"
Manifests:
  - Platform:
      os: linux
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/bundle.zip"
        Unarchive: ZIP
    Lifecycle:
      Run:
        Setenv:
          PYTHONPATH: "{artifacts:decompressedPath}/bundle"
        Script: |-
          python3 -u {artifacts:decompressedPath}/bundle/main.py \
            --path "{configuration:/Path}" \
            --interval "{configuration:/Interval}" \
            --processor_stream_name "{configuration:/Processor/StreamName}" \
            --processor_batch_size "{configuration:/Processor/BatchSize}" \
            --uploader_bucket_name "{configuration:/Uploader/BucketName}" \
            --uploader_prefix "{configuration:/Uploader/Prefix}" \
            --log_level "{configuration:/LogLevel}"
