name: Greengrass Component Deploy - aws-greengrass-json-gzip

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GREENGRASS_COMPONENT_NAME: com.devopstar.json.gzip
  GREENGRASS_REGION: ap-southeast-2
  GREENGRASS_DEV_KIT_VERSION: v1.2.3

jobs:
  publish:
    name: Component publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      published_version: ${{ steps.gdk_version.outputs.version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.OIDC_ROLE_AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.OIDC_ROLE_AWS_REGION }}

    - name: Install Greengrass Development Kit
      run: pip install -U git+https://github.com/aws-greengrass/aws-greengrass-gdk-cli.git@${{ env.GREENGRASS_DEV_KIT_VERSION }}

    - name: GDK Build
      run: gdk component build
      env:
        AWS_REGION: ${{ env.GREENGRASS_REGION }}

    - name: GDK Publish
      run: gdk component publish

    - name: Get published version
      id: gdk_version
      run: |
        export AWS_ACCOUNT_ID=$(aws sts get-caller-identity |  jq -r '.Account')
        export AWS_REGION=${GREENGRASS_REGION}
        export LATEST_COMPONENT_VERSION=$(aws greengrassv2 list-component-versions \
          --output text \
          --no-paginate \
          --arn arn:aws:greengrass:${AWS_REGION}:${AWS_ACCOUNT_ID}:components:${GREENGRASS_COMPONENT_NAME} \
          --query 'componentVersions[0].componentVersion')

        echo "version=${LATEST_COMPONENT_VERSION}" >> $GITHUB_OUTPUT
